import { AuroraBackground } from "@/components/ui/aurora-background";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./global.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} relative z-10`}>
        <AuroraBackground className="absolute inset-0 z-0">
          {children}
        </AuroraBackground>
      </body>
    </html>
  );
}
